In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.formula.api as smf

## data load in

In [15]:
path = "Data/gas_coordinates.csv"
gas = pd.read_csv(path)
gas["date"] = pd.to_datetime(gas["date"])
gas["month"] = gas["date"].dt.month

gas.head()

,metro,date,regular,mid,premium,diesel,reg_delt,met,lat,lng,month
0,Bradenton-Sarasota-Venice,2022-01-21,3.236000,3.625,3.915000,3.563000,NaN,North Port-Bradenton-Sarasota,27.3479,-82.3223,1
1,Bradenton-Sarasota-Venice,2022-01-22,3.254667,3.639,3.929667,3.587667,0.576844,North Port-Bradenton-Sarasota,27.3479,-82.3223,1
2,Bradenton-Sarasota-Venice,2022-01-23,3.273333,3.653,3.944333,3.612333,0.573535,North Port-Bradenton-Sarasota,27.3479,-82.3223,1
3,Bradenton-Sarasota-Venice,2022-01-24,3.292000,3.667,3.959000,3.637000,0.570265,North Port-Bradenton-Sarasota,27.3479,-82.3223,1
4,Bradenton-Sarasota-Venice,2022-01-25,3.310667,3.681,3.973667,3.661667,0.567031,North Port-Bradenton-Sarasota,27.3479,-82.3223,1

In [25]:
path = "Data/ignore/hurr_mod.csv"
hurricanes = pd.read_csv(path)
hurricanes["date"] = pd.to_datetime(hurricanes["DATE"])

## combining

In [26]:
gas['date'].dtype == hurricanes['date'].dtype

True

In [20]:
hurricanes.isna().sum()

SID                  0
SEASON               0
NAME                 0
MAX CAT              0
START DATE           0
END DATE             0
STORM DURATION       0
ISO_TIME             0
NATURE               0
DIST2LAND            0
LANDFALL            32
USA_LAT              0
USA_LON              0
USA_RECORD           0
USA_STATUS           0
USA_WIND             0
USA_PRES             0
USA_SSHS             0
USA_POCI             6
USA_ROCI             6
USA_RMW              0
USA_EYE           2624
USA_GUST             0
USA_SEAHGT        1012
STORM_SPEED          0
STORM_DIR            0
DATE                 0
dtype: int64

distance with euclidean measure

In [21]:
hurricanes.shape

(2661, 27)

In [27]:
hurricanes = hurricanes.drop_duplicates(subset = "date", keep = "first")
hurricanes.shape

(254, 28)

In [24]:
gas.shape

(34560, 11)

In [28]:
panel = gas.merge(hurricanes, on = "date", how = "left")
panel.shape

(34560, 38)

In [30]:
panel.head()

,metro,date,regular,mid,premium,diesel,reg_delt,met,lat,lng,...,USA_SSHS,USA_POCI,USA_ROCI,USA_RMW,USA_EYE,USA_GUST,USA_SEAHGT,STORM_SPEED,STORM_DIR,DATE
0,Bradenton-Sarasota-Venice,2022-01-21,3.236000,3.625,3.915000,3.563000,NaN,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bradenton-Sarasota-Venice,2022-01-22,3.254667,3.639,3.929667,3.587667,0.576844,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bradenton-Sarasota-Venice,2022-01-23,3.273333,3.653,3.944333,3.612333,0.573535,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bradenton-Sarasota-Venice,2022-01-24,3.292000,3.667,3.959000,3.637000,0.570265,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bradenton-Sarasota-Venice,2022-01-25,3.310667,3.681,3.973667,3.661667,0.567031,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
hurricanes.columns

Index(['SID', 'SEASON', 'NAME', 'MAX CAT', 'START DATE', 'END DATE',
       'STORM DURATION', 'ISO_TIME', 'NATURE', 'DIST2LAND', 'LANDFALL',
       'USA_LAT', 'USA_LON', 'USA_RECORD', 'USA_STATUS', 'USA_WIND',
       'USA_PRES', 'USA_SSHS', 'USA_POCI', 'USA_ROCI', 'USA_RMW', 'USA_EYE',
       'USA_GUST', 'USA_SEAHGT', 'STORM_SPEED', 'STORM_DIR', 'DATE', 'date'],
      dtype='str')

In [37]:
print("gas:", gas.shape)
print("hurricanes:", hurricanes.shape)
print("panel:", panel.shape)

panel[["date", "met", "lat", "lng", "USA_LAT", "USA_LON"]].head(10)

gas: (34560, 11)
hurricanes: (254, 28)
panel: (34560, 38)

,date,met,lat,lng,USA_LAT,USA_LON
0,2022-01-21,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
1,2022-01-22,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
2,2022-01-23,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
3,2022-01-24,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
4,2022-01-25,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
5,2022-01-26,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
6,2022-01-27,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
7,2022-01-28,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
8,2022-01-29,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
9,2022-01-30,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN

In [40]:
panel["distance"] = np.sqrt(
    (panel["lat"] - panel['USA_LAT'])**2 + 
    (panel["lng"] - panel['USA_LON'])**2
)

In [41]:
panel.head()

,metro,date,regular,mid,premium,diesel,reg_delt,met,lat,lng,...,USA_POCI,USA_ROCI,USA_RMW,USA_EYE,USA_GUST,USA_SEAHGT,STORM_SPEED,STORM_DIR,DATE,distance
0,Bradenton-Sarasota-Venice,2022-01-21,3.236000,3.625,3.915000,3.563000,NaN,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bradenton-Sarasota-Venice,2022-01-22,3.254667,3.639,3.929667,3.587667,0.576844,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bradenton-Sarasota-Venice,2022-01-23,3.273333,3.653,3.944333,3.612333,0.573535,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bradenton-Sarasota-Venice,2022-01-24,3.292000,3.667,3.959000,3.637000,0.570265,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bradenton-Sarasota-Venice,2022-01-25,3.310667,3.681,3.973667,3.661667,0.567031,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
panel.to_csv("../Data/ignore/panel_data.csv", index = False)

## Simple regression

In [ ]:
reg1 = smf.ols("regular ~ distance", data = panel).fit()
print(reg1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                regular   R-squared:                       0.010
Model:                            OLS   Adj. R-squared:                  0.010
Method:                 Least Squares   F-statistic:                     64.05
Date:                Fri, 27 Mar 2026   Prob (F-statistic):           1.43e-15
Time:                        10:28:44   Log-Likelihood:                -2788.0
No. Observations:                6312   AIC:                             5580.
Df Residuals:                    6310   BIC:                             5593.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.4316      0.009    384.315      0.000       3.414       3.449
distance      -0.0022      0.000     -8.003      0.000      -0.003      -0.002
==============================================================================
Omnibus:                     2974.201   Durbin-Watson:                   0.094
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            13418.683
Skew:                           2.358   Prob(JB):                         0.00
Kurtosis:                       8.365   Cond. No.                         61.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
reg2 = smf.ols("regular ~ distance + C(met)", data = panel).fit()
print(reg2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                regular   R-squared:                       0.047
Model:                            OLS   Adj. R-squared:                  0.043
Method:                 Least Squares   F-statistic:                     13.95
Date:                Fri, 27 Mar 2026   Prob (F-statistic):           1.20e-50
Time:                        10:28:44   Log-Likelihood:                -2669.5
No. Observations:                6312   AIC:                             5385.
Df Residuals:                    6289   BIC:                             5540.
Df Model:                          22
Covariance Type:            nonrobust
=====================================================================================================================
                                                        coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------
Intercept                                             3.4371      0.024    143.457      0.000       3.390       3.484
C(met)[T.Crestview-Fort Walton Beach-Destin]         -0.1936      0.032     -5.998      0.000      -0.257      -0.130
C(met)[T.Deltona-Daytona Beach-Ormond Beach]         -0.0041      0.032     -0.126      0.900      -0.067       0.059
C(met)[T.Gainesville]                                 0.0611      0.032      1.895      0.058      -0.002       0.124
C(met)[T.Homosassa Springs]                           0.0147      0.032      0.454      0.649      -0.049       0.078
C(met)[T.Jacksonville]                               -0.0242      0.032     -0.748      0.454      -0.087       0.039
C(met)[T.Lakeland-Winter Haven]                      -0.0085      0.032     -0.264      0.792      -0.072       0.055
C(met)[T.Miami-Fort Lauderdale-West Palm Beach]       0.0837      0.026      3.178      0.001       0.032       0.135
C(met)[T.Naples-Marco Island]                         0.0821      0.032      2.545      0.011       0.019       0.145
C(met)[T.North Port-Bradenton-Sarasota]              -0.0071      0.032     -0.220      0.826      -0.070       0.056
C(met)[T.Ocala]                                      -0.0065      0.032     -0.200      0.841      -0.070       0.057
C(met)[T.Orlando-Kissimmee-Sanford]                  -0.0463      0.032     -1.436      0.151      -0.110       0.017
C(met)[T.Palm Bay-Melbourne-Titusville]              -0.0440      0.032     -1.365      0.172      -0.107       0.019
C(met)[T.Panama City-Panama City Beach]              -0.1407      0.032     -4.358      0.000      -0.204      -0.077
C(met)[T.Pensacola-Ferry Pass-Brent]                 -0.1731      0.032     -5.363      0.000      -0.236      -0.110
C(met)[T.Port St. Lucie]                              0.0275      0.032      0.853      0.394      -0.036       0.091
C(met)[T.Punta Gorda]                                -0.0360      0.032     -1.115      0.265      -0.099       0.027
C(met)[T.Sebastian-Vero Beach-West Vero Corridor]    -0.0137      0.032     -0.425      0.671      -0.077       0.050
C(met)[T.Sebring]                                     0.0086      0.032      0.266      0.790      -0.055       0.072
C(met)[T.Tallahassee]                                 0.0287      0.032      0.890      0.374      -0.035       0.092
C(met)[T.Tampa-St. Petersburg-Clearwater]            -0.0198      0.032     -0.613      0.540      -0.083       0.043
C(met)[T.Wildwood-The Villages]                      -0.0396      0.032     -1.229      0.219      -0.103       0.024
distance                                             -0.0020      0.000     -7.272      0.000      -0.002      -0.001
==============================================================================
Omnibus:                     3174.751   Durbin-Watson:                   0.096
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            15509.106
Skew:                           2.516   Prob(JB):                         0.00
Kurtosis:                       8.801   Cond. No.                         768.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
panel.head()

,metro,date,regular,mid,premium,diesel,reg_delt,met,lat_x,lng,...,nature,lat_y,lon,wmo_wind,dist2land,landfall,usa_sshs,storm_speed,usa_roci,distance
0,Bradenton-Sarasota-Venice,2022-01-21,3.236000,3.625,3.915000,3.563000,NaN,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bradenton-Sarasota-Venice,2022-01-22,3.254667,3.639,3.929667,3.587667,0.576844,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bradenton-Sarasota-Venice,2022-01-23,3.273333,3.653,3.944333,3.612333,0.573535,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bradenton-Sarasota-Venice,2022-01-24,3.292000,3.667,3.959000,3.637000,0.570265,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bradenton-Sarasota-Venice,2022-01-25,3.310667,3.681,3.973667,3.661667,0.567031,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
reg3 = smf.ols("regular ~ distance + dist2land + storm_speed + wmo_wind", data = panel).fit()
print(reg3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                regular   R-squared:                       0.049
Model:                            OLS   Adj. R-squared:                  0.048
Method:                 Least Squares   F-statistic:                     80.87
Date:                Fri, 27 Mar 2026   Prob (F-statistic):           4.86e-67
Time:                        10:29:14   Log-Likelihood:                -2662.0
No. Observations:                6312   AIC:                             5334.
Df Residuals:                    6307   BIC:                             5368.
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept       3.3747      0.014    233.000      0.000       3.346       3.403
distance       -0.0018      0.000     -4.979      0.000      -0.002      -0.001
dist2land   -7.354e-05      1e-05     -7.352      0.000   -9.31e-05   -5.39e-05
storm_speed     0.0086      0.001     11.858      0.000       0.007       0.010
wmo_wind    -6.524e-05      0.000     -0.317      0.751      -0.000       0.000
==============================================================================
Omnibus:                     2745.438   Durbin-Watson:                   0.131
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            11209.270
Skew:                           2.188   Prob(JB):                         0.00
Kurtosis:                       7.845   Cond. No.                     2.81e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.81e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
from sklearn.model_selection import train_test_split
p2 = panel.dropna(subset=["reg_delt", "distance", "dist2land", "storm_speed"])

X = p2[["distance", "dist2land", "storm_speed"]]
y = p2["reg_delt"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=.2,
)

training = pd.concat([X_train, y_train])

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print(reg_log_linear.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.059
Model:                            OLS   Adj. R-squared:                  0.058
Method:                 Least Squares   F-statistic:                     131.0
Date:                Fri, 27 Mar 2026   Prob (F-statistic):           2.49e-82
Time:                        10:46:55   Log-Likelihood:                -4691.1
No. Observations:                6312   AIC:                             9390.
Df Residuals:                    6308   BIC:                             9417.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.1967      0.015     13.032      0.000       0.167       0.226
X[0]          -0.0036      0.000     -7.584      0.000      -0.005      -0.003
X[1]          -0.0001   1.37e-05     -9.840      0.000      -0.000      -0.000
X[2]          -0.0020      0.001     -2.038      0.042      -0.004   -7.52e-05
==============================================================================
Omnibus:                     2948.510   Durbin-Watson:                   1.233
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            42169.163
Skew:                           1.864   Prob(JB):                         0.00
Kurtosis:                      15.101   Cond. No.                     2.12e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.12e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
y_pred = model.predict(X_test)

x = sum(y_pred - y_test)
x = x**2
print(x)

76.89730539996978

In [ ]:
coeffs = pd.DataFrame({
    "feature": X.columns,
    "coefficient":model.coef_ 
})

print(coeffs)

       feature  coefficient
0     distance    -0.003594
1    dist2land    -0.000137
2  storm_speed    -0.001604

In [ ]:
panel["log_price"] = np.log(panel["regular"])

reg_log_linear = smf.ols("log_price ~ distance", data = panel).fit()

print(reg_log_linear.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              log_price   R-squared:                       0.010
Model:                            OLS   Adj. R-squared:                  0.010
Method:                 Least Squares   F-statistic:                     66.43
Date:                Thu, 26 Mar 2026   Prob (F-statistic):           4.34e-16
Time:                        04:03:47   Log-Likelihood:                 5572.8
No. Observations:                6312   AIC:                        -1.114e+04
Df Residuals:                    6310   BIC:                        -1.113e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.2262      0.002    516.426      0.000       1.222       1.231
distance      -0.0006   7.26e-05     -8.150      0.000      -0.001      -0.000
==============================================================================
Omnibus:                     2561.427   Durbin-Watson:                   0.091
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9541.578
Skew:                           2.061   Prob(JB):                         0.00
Kurtosis:                       7.392   Cond. No.                         61.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## MLR

In [ ]:
reg_delt = smf.ols("reg_delt ~ distance + dist2land + storm_speed + C(date)", data = panel).fit()

print(reg_delt.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               reg_delt   R-squared:                       0.770
Model:                            OLS   Adj. R-squared:                  0.760
Method:                 Least Squares   F-statistic:                     77.11
Date:                Thu, 26 Mar 2026   Prob (F-statistic):               0.00
Time:                        04:03:48   Log-Likelihood:                -239.59
No. Observations:                6312   AIC:                             1007.
Df Residuals:                    6048   BIC:                             2789.
Df Model:                         263
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 0.1578      0.016      9.723      0.000       0.126       0.190
C(date)[T.2022-01-22] -7.797e-13   1.69e-13     -4.621      0.000   -1.11e-12   -4.49e-13
C(date)[T.2022-01-23]  6.205e-13   4.98e-14     12.455      0.000    5.23e-13    7.18e-13
C(date)[T.2022-01-24]  -1.56e-14    3.1e-14     -0.503      0.615   -7.64e-14    4.52e-14
C(date)[T.2022-01-25]  1.081e-13   1.46e-14      7.414      0.000    7.95e-14    1.37e-13
C(date)[T.2022-01-26]  3.675e-14   1.21e-14      3.033      0.002     1.3e-14    6.05e-14
C(date)[T.2022-01-27]  6.626e-15   1.48e-14      0.446      0.655   -2.25e-14    3.57e-14
C(date)[T.2022-01-28] -3.911e-14   4.93e-15     -7.930      0.000   -4.88e-14   -2.94e-14
C(date)[T.2022-01-29] -4.532e-14   8.16e-14     -0.555      0.579   -2.05e-13    1.15e-13
C(date)[T.2022-01-30] -2.317e-14   1.55e-14     -1.492      0.136   -5.36e-14    7.28e-15
C(date)[T.2022-01-31]  -2.04e-13   1.34e-14    -15.200      0.000    -2.3e-13   -1.78e-13
C(date)[T.2022-02-01]  3.649e-14   4.03e-15      9.066      0.000    2.86e-14    4.44e-14
C(date)[T.2022-02-02] -9.334e-15   1.39e-14     -0.670      0.503   -3.66e-14     1.8e-14
C(date)[T.2022-02-03]   -7.6e-13   1.06e-13     -7.201      0.000   -9.67e-13   -5.53e-13
C(date)[T.2022-02-04]  8.084e-14   4.52e-14      1.790      0.073   -7.69e-15    1.69e-13
C(date)[T.2022-02-05]  2.133e-14    1.5e-14      1.421      0.155    -8.1e-15    5.08e-14
C(date)[T.2022-02-06]  6.723e-15   4.13e-14      0.163      0.871   -7.42e-14    8.77e-14
C(date)[T.2022-02-07]  -4.87e-14   9.07e-15     -5.368      0.000   -6.65e-14   -3.09e-14
C(date)[T.2022-02-08]  1.225e-13   1.59e-14      7.696      0.000    9.13e-14    1.54e-13
C(date)[T.2022-02-09]  9.516e-13    8.3e-14     11.468      0.000    7.89e-13    1.11e-12
C(date)[T.2022-02-10]  1.482e-14   1.15e-14      1.292      0.196   -7.66e-15    3.73e-14
C(date)[T.2022-02-11] -7.157e-14   1.09e-14     -6.572      0.000   -9.29e-14   -5.02e-14
C(date)[T.2022-02-12] -4.234e-13   6.95e-14     -6.093      0.000    -5.6e-13   -2.87e-13
C(date)[T.2022-02-13] -8.378e-14   1.74e-14     -4.828      0.000   -1.18e-13   -4.98e-14
C(date)[T.2022-02-14] -2.704e-14   1.33e-14     -2.031      0.042   -5.31e-14   -9.44e-16
C(date)[T.2022-02-15] -3.985e-13   7.87e-14     -5.061      0.000   -5.53e-13   -2.44e-13
C(date)[T.2022-02-16]  1.352e-14   1.46e-14      0.923      0.356   -1.52e-14    4.22e-14
C(date)[T.2022-02-17]  2.128e-13   1.57e-14     13.515      0.000    1.82e-13    2.44e-13
C(date)[T.2022-02-18] -1.559e-13   8.79e-14     -1.773      0.076   -3.28e-13    1.65e-14
C(date)[T.2022-02-19]   2.72e-14    1.7e-14      1.599      0.110   -6.15e-15    6.06e-14
C(date)[T.2022-02-20]  1.008e-13   8.73e-14      1.154      0.248   -7.04e-14    2.72e-13
C(date)[T.2022-02-21]   1.89e-14   6.17e-15      3.063      0.002    6.81e-15     3.1e-14
C(date)[T.2022-02-22] -1.205e-14   1.11e-14     -1.084      0.279   -3.39e-14    9.75e-15
C(date)[T.2022-02-23] -1.701e-14   4.76e-15     -3.572      0.000   -2.63e-14   -7.68e-15
C(date)[T.2022-02-24]  -5.81e-14   1.94e-14     -2.996      0.003   -9.61e-14   -2.01e-14
C(date)[T.2022-02-25]  1.605e-14    1.7e-14      0.946      0.344   -1.72e-14    4.93e-14
C(date)[T.2022-02-26] -5.834e-14   9.36e-15     -6.232      0.000   -7.67e-14      -4e-14
C(date)[T.2022-02-27]  6.296e-14    1.4e-14      4.503      0.000    3.55e-14    9.04e-14
C(date)[T.2022-02-28]   7.45e-14   1.31e-14      5.678      0.000    4.88e-14       1e-13
C(date)[T.2022-03-01]  1.649e-14   1.26e-14      1.307      0.191   -8.24e-15    4.12e-14
C(date)[T.2022-03-02]  5.474e-14   8.67e-15      6.316      0.000    3.78e-14    7.17e-14
C(date)[T.2022-03-03] -1.714e-13   1.96e-14     -8.726      0.000    -2.1e-13   -1.33e-13
C(date)[T.2022-03-04]  1.265e-14   9.34e-15      1.354      0.176   -5.66e-15     3.1e-14
C(date)[T.2022-03-05] -2.189e-14   1.27e-14     -1.718      0.086   -4.69e-14    3.08e-15
C(date)[T.2022-03-06] -8.029e-14   1.45e-14     -5.541      0.000   -1.09e-13   -5.19e-14
C(date)[T.2022-03-07]  5.568e-14   8.26e-15      6.742      0.000    3.95e-14    7.19e-14
C(date)[T.2022-03-08] -1.036e-13   1.42e-14     -7.296      0.000   -1.31e-13   -7.58e-14
C(date)[T.2022-03-09] -8.347e-14   1.72e-14     -4.848      0.000   -1.17e-13   -4.97e-14
C(date)[T.2022-03-10] -4.026e-14   1.15e-14     -3.510      0.000   -6.27e-14   -1.78e-14
C(date)[T.2022-03-11] -7.684e-14   1.18e-14     -6.493      0.000      -1e-13   -5.36e-14
C(date)[T.2022-03-12] -4.694e-14   1.41e-14     -3.330      0.001   -7.46e-14   -1.93e-14
C(date)[T.2022-03-13] -7.343e-14   1.52e-14     -4.832      0.000   -1.03e-13   -4.36e-14
C(date)[T.2022-03-14]  2.961e-15   1.47e-14      0.202      0.840   -2.58e-14    3.17e-14
C(date)[T.2022-03-15]  1.389e-13   1.96e-14      7.088      0.000       1e-13    1.77e-13
C(date)[T.2022-03-16]  4.098e-14   1.37e-14      2.983      0.003     1.4e-14    6.79e-14
C(date)[T.2022-03-17] -4.148e-14   1.79e-14     -2.321      0.020   -7.65e-14   -6.45e-15
C(date)[T.2022-03-18] -2.039e-14   1.21e-14     -1.681      0.093   -4.42e-14    3.39e-15
C(date)[T.2022-03-19]  7.389e-14   1.19e-14      6.216      0.000    5.06e-14    9.72e-14
C(date)[T.2022-03-20] -1.538e-15   1.59e-14     -0.097      0.923   -3.28e-14    2.97e-14
C(date)[T.2022-03-21] -1.954e-14   1.35e-14     -1.448      0.148    -4.6e-14    6.91e-15
C(date)[T.2022-03-22] -4.331e-14   1.88e-14     -2.302      0.021   -8.02e-14   -6.43e-15
C(date)[T.2022-03-23]  1.207e-13   1.35e-14      8.911      0.000    9.42e-14    1.47e-13
C(date)[T.2022-03-24] -5.684e-14   1.06e-14     -5.378      0.000   -7.76e-14   -3.61e-14
C(date)[T.2022-03-25]  4.217e-14   1.23e-14      3.442      0.001    1.82e-14    6.62e-14
C(date)[T.2022-03-26] -8.349e-14   1.15e-14     -7.287      0.000   -1.06e-13    -6.1e-14
C(date)[T.2022-03-27]  7.209e-14   1.53e-14      4.727      0.000    4.22e-14    1.02e-13
C(date)[T.2022-03-28] -5.286e-14   1.42e-14     -3.726      0.000   -8.07e-14    -2.5e-14
C(date)[T.2022-03-29] -2.059e-13   1.43e-14    -14.417      0.000   -2.34e-13   -1.78e-13
C(date)[T.2022-03-30]  1.653e-14   1.63e-14      1.011      0.312   -1.55e-14    4.86e-14
C(date)[T.2022-03-31]  3.539e-14   1.68e-14      2.111      0.035    2.52e-15    6.83e-14
C(date)[T.2022-04-01]  1.251e-14   1.06e-14      1.178      0.239   -8.31e-15    3.33e-14
C(date)[T.2022-04-02] -2.601e-15   1.54e-14     -0.169      0.866   -3.28e-14    2.76e-14
C(date)[T.2022-04-03] -1.932e-14   1.47e-14     -1.310      0.190   -4.82e-14    9.59e-15
C(date)[T.2022-04-04] -2.219e-14   1.33e-14     -1.674      0.094   -4.82e-14     3.8e-15
C(date)[T.2022-04-05]  6.539e-14   1.12e-14      5.817      0.000    4.34e-14    8.74e-14
C(date)[T.2022-04-06] -2.086e-13   1.29e-14    -16.155      0.000   -2.34e-13   -1.83e-13
C(date)[T.2022-04-07] -9.675e-14   1.74e-14     -5.551      0.000   -1.31e-13   -6.26e-14
C(date)[T.2022-04-08] -8.535e-14   1.39e-14     -6.146      0.000   -1.13e-13   -5.81e-14
C(date)[T.2022-04-09]  2.972e-14   1.53e-14      1.944      0.052   -2.48e-16    5.97e-14
C(date)[T.2022-04-10]  -5.66e-14   1.27e-14     -4.447      0.000   -8.16e-14   -3.16e-14
C(date)[T.2022-04-11]    1.5e-14      1e-14      1.494      0.135   -4.68e-15    3.47e-14
C(date)[T.2022-04-12] -2.423e-15   1.39e-14     -0.175      0.861   -2.96e-14    2.47e-14
C(date)[T.2022-04-13]  7.028e-15   1.25e-14      0.561      0.575   -1.75e-14    3.16e-14
C(date)[T.2022-04-14] -1.816e-13    1.3e-14    -13.941      0.000   -2.07e-13   -1.56e-13
C(date)[T.2022-04-15]  8.471e-14   1.41e-14      5.994      0.000     5.7e-14    1.12e-13
C(date)[T.2022-04-16] -1.815e-14    1.4e-14     -1.294      0.196   -4.57e-14    9.36e-15
C(date)[T.2022-04-17]   3.13e-14   1.45e-14      2.153      0.031     2.8e-15    5.98e-14
C(date)[T.2022-04-18]  3.779e-14   1.22e-14      3.092      0.002    1.38e-14    6.17e-14
C(date)[T.2022-04-19] -4.038e-14    1.1e-14     -3.659      0.000    -6.2e-14   -1.87e-14
C(date)[T.2022-04-20]  7.377e-15    1.6e-14      0.462      0.644   -2.39e-14    3.87e-14
C(date)[T.2022-04-21] -5.622e-14   1.12e-14     -5.035      0.000   -7.81e-14   -3.43e-14
C(date)[T.2022-04-22]  -1.07e-13   1.74e-14     -6.145      0.000   -1.41e-13   -7.29e-14
C(date)[T.2022-04-23] -8.221e-14   1.42e-14     -5.786      0.000    -1.1e-13   -5.44e-14
C(date)[T.2022-04-24]  2.206e-13   1.51e-14     14.597      0.000    1.91e-13     2.5e-13
C(date)[T.2022-04-25]  2.562e-14   1.19e-14      2.144      0.032    2.19e-15     4.9e-14
C(date)[T.2022-04-26]  5.594e-14   1.08e-14      5.186      0.000    3.48e-14    7.71e-14
C(date)[T.2022-04-27]  -5.27e-16   1.23e-14     -0.043      0.966   -2.47e-14    2.36e-14
C(date)[T.2022-04-28]   1.08e-13    1.5e-14      7.221      0.000    7.87e-14    1.37e-13
C(date)[T.2022-04-29] -3.856e-14   1.34e-14     -2.878      0.004   -6.48e-14   -1.23e-14
C(date)[T.2022-04-30] -1.305e-13   1.24e-14    -10.561      0.000   -1.55e-13   -1.06e-13
C(date)[T.2022-05-01] -6.798e-14   1.43e-14     -4.738      0.000   -9.61e-14   -3.99e-14
C(date)[T.2022-05-02] -4.655e-14   1.46e-14     -3.193      0.001   -7.51e-14    -1.8e-14
C(date)[T.2022-05-03]  8.222e-15    1.5e-14      0.549      0.583   -2.11e-14    3.76e-14
C(date)[T.2022-05-04] -2.218e-14   1.14e-14     -1.941      0.052   -4.46e-14    2.21e-16
C(date)[T.2022-05-05]   9.97e-14   1.39e-14      7.172      0.000    7.24e-14    1.27e-13
C(date)[T.2022-05-06]  1.768e-13   1.08e-14     16.317      0.000    1.56e-13    1.98e-13
C(date)[T.2022-05-07] -3.274e-14   1.54e-14     -2.126      0.034   -6.29e-14   -2.55e-15
C(date)[T.2022-05-08] -5.754e-14   1.29e-14     -4.476      0.000   -8.27e-14   -3.23e-14
C(date)[T.2022-05-09]  7.832e-14   1.16e-14      6.771      0.000    5.56e-14    1.01e-13
C(date)[T.2022-05-10] -4.309e-14   1.62e-14     -2.662      0.008   -7.48e-14   -1.14e-14
C(date)[T.2022-05-11]  1.598e-14   1.01e-14      1.590      0.112   -3.73e-15    3.57e-14
C(date)[T.2022-05-12] -7.042e-14   1.17e-14     -6.027      0.000   -9.33e-14   -4.75e-14
C(date)[T.2022-05-13]  1.195e-13   1.51e-14      7.923      0.000       9e-14    1.49e-13
C(date)[T.2022-05-14] -2.522e-14   1.15e-14     -2.201      0.028   -4.77e-14   -2.76e-15
C(date)[T.2022-05-15] -3.761e-14   1.11e-14     -3.400      0.001   -5.93e-14   -1.59e-14
C(date)[T.2022-05-16]  9.733e-14   1.62e-14      5.999      0.000    6.55e-14    1.29e-13
C(date)[T.2022-05-17] -8.783e-14   9.49e-15     -9.258      0.000   -1.06e-13   -6.92e-14
C(date)[T.2022-05-18]  5.802e-14   1.77e-14      3.274      0.001    2.33e-14    9.28e-14
C(date)[T.2022-05-19] -7.371e-14   1.24e-14     -5.944      0.000    -9.8e-14   -4.94e-14
C(date)[T.2022-05-20] -2.375e-14   1.08e-14     -2.196      0.028    -4.5e-14   -2.55e-15
C(date)[T.2022-05-21]  6.646e-15   1.16e-14      0.573      0.567   -1.61e-14    2.94e-14
C(date)[T.2022-05-22]  5.868e-14   1.39e-14      4.232      0.000    3.15e-14    8.59e-14
C(date)[T.2022-05-23]  3.091e-14   1.29e-14      2.395      0.017    5.61e-15    5.62e-14
C(date)[T.2022-05-24] -1.763e-13   1.47e-14    -11.990      0.000   -2.05e-13   -1.47e-13
C(date)[T.2022-05-25] -1.034e-13   1.49e-14     -6.947      0.000   -1.33e-13   -7.42e-14
C(date)[T.2022-05-26]  1.039e-13   1.79e-14      5.818      0.000    6.89e-14    1.39e-13
C(date)[T.2022-05-27]  -8.19e-14   2.06e-14     -3.985      0.000   -1.22e-13   -4.16e-14
C(date)[T.2022-05-28]  1.826e-13   1.64e-14     11.123      0.000     1.5e-13    2.15e-13
C(date)[T.2022-05-29] -2.156e-13   1.54e-14    -13.974      0.000   -2.46e-13   -1.85e-13
C(date)[T.2022-05-30]  5.382e-14   1.68e-14      3.200      0.001    2.08e-14    8.68e-14
C(date)[T.2022-05-31]  4.611e-14   1.15e-14      4.008      0.000    2.36e-14    6.87e-14
C(date)[T.2022-06-01] -7.634e-14   1.43e-14     -5.332      0.000   -1.04e-13   -4.83e-14
C(date)[T.2022-06-02]     1.3683      0.052     26.253      0.000       1.266       1.470
C(date)[T.2022-06-03]     0.1446      0.052      2.770      0.006       0.042       0.247
C(date)[T.2022-06-04]     0.2442      0.061      3.977      0.000       0.124       0.365
C(date)[T.2022-06-05]     0.2373      0.062      3.799      0.000       0.115       0.360
C(date)[T.2022-06-06]     0.2761      0.066      4.171      0.000       0.146       0.406
C(date)[T.2022-06-07]  -9.09e-14   1.39e-14     -6.542      0.000   -1.18e-13   -6.37e-14
C(date)[T.2022-06-08] -3.912e-14   1.03e-14     -3.810      0.000   -5.92e-14    -1.9e-14
C(date)[T.2022-06-09]  1.113e-13   1.65e-14      6.738      0.000    7.89e-14    1.44e-13
C(date)[T.2022-06-10] -1.406e-14   1.21e-14     -1.163      0.245   -3.78e-14    9.63e-15
C(date)[T.2022-06-11] -7.144e-14   1.09e-14     -6.540      0.000   -9.29e-14      -5e-14
C(date)[T.2022-06-12]  -1.32e-14   1.16e-14     -1.142      0.253   -3.59e-14    9.46e-15
C(date)[T.2022-06-13] -2.722e-14   1.55e-14     -1.757      0.079   -5.76e-14    3.15e-15
C(date)[T.2022-06-14]    8.8e-14   1.06e-14      8.279      0.000    6.72e-14    1.09e-13
C(date)[T.2022-06-15]  6.826e-14   1.51e-14      4.508      0.000    3.86e-14    9.79e-14
C(date)[T.2022-06-16] -1.131e-13   1.73e-14     -6.536      0.000   -1.47e-13   -7.92e-14
C(date)[T.2022-06-17] -1.792e-14   1.22e-14     -1.472      0.141   -4.18e-14    5.95e-15
C(date)[T.2022-06-18] -7.631e-14   1.45e-14     -5.274      0.000   -1.05e-13   -4.79e-14
C(date)[T.2022-06-19]  2.658e-14   1.14e-14      2.338      0.019    4.29e-15    4.89e-14
C(date)[T.2022-06-20] -3.497e-14   1.19e-14     -2.940      0.003   -5.83e-14   -1.17e-14
C(date)[T.2022-06-21]  3.722e-14   1.47e-14      2.527      0.012    8.35e-15    6.61e-14
C(date)[T.2022-06-22] -1.207e-13      1e-14    -12.052      0.000    -1.4e-13   -1.01e-13
C(date)[T.2022-06-23] -4.794e-14   1.11e-14     -4.326      0.000   -6.97e-14   -2.62e-14
C(date)[T.2022-06-24] -4.604e-14   8.45e-15     -5.449      0.000   -6.26e-14   -2.95e-14
C(date)[T.2022-06-25]  6.521e-14    1.4e-14      4.642      0.000    3.77e-14    9.27e-14
C(date)[T.2022-06-26] -1.625e-14   9.15e-15     -1.776      0.076   -3.42e-14    1.68e-15
C(date)[T.2022-06-27]    -0.1895      0.056     -3.384      0.001      -0.299      -0.080
C(date)[T.2022-06-28]    -0.7825      0.054    -14.371      0.000      -0.889      -0.676
C(date)[T.2022-06-29]    -0.4310      0.052     -8.320      0.000      -0.533      -0.329
C(date)[T.2022-06-30]    -0.2749      0.052     -5.272      0.000      -0.377      -0.173
C(date)[T.2022-07-01]    -0.3848      0.054     -7.180      0.000      -0.490      -0.280
C(date)[T.2022-07-02]    -0.6090      0.052    -11.669      0.000      -0.711      -0.507
C(date)[T.2022-07-03]    -0.4057      0.053     -7.699      0.000      -0.509      -0.302
C(date)[T.2022-07-04]    -0.4947      0.053     -9.295      0.000      -0.599      -0.390
C(date)[T.2022-07-05]    -0.5203      0.052     -9.960      0.000      -0.623      -0.418
C(date)[T.2022-07-06]    -0.5112      0.053     -9.684      0.000      -0.615      -0.408
C(date)[T.2022-07-07]    -0.4738      0.053     -8.963      0.000      -0.577      -0.370
C(date)[T.2022-07-08]    -0.4142      0.052     -7.907      0.000      -0.517      -0.312
C(date)[T.2022-07-09]    -0.3273      0.052     -6.278      0.000      -0.429      -0.225
C(date)[T.2022-07-10]    -0.0688      0.052     -1.323      0.186      -0.171       0.033
C(date)[T.2022-07-11]    -0.2813      0.053     -5.280      0.000      -0.386      -0.177
C(date)[T.2022-07-12]  1.251e-14   1.07e-14      1.166      0.244   -8.52e-15    3.35e-14
C(date)[T.2022-07-13] -8.302e-14   1.37e-14     -6.058      0.000    -1.1e-13   -5.62e-14
C(date)[T.2022-07-14]   1.76e-14   1.39e-14      1.268      0.205   -9.61e-15    4.48e-14
C(date)[T.2022-07-15] -1.848e-13   1.59e-14    -11.622      0.000   -2.16e-13   -1.54e-13
C(date)[T.2022-07-16] -1.346e-13   1.34e-14    -10.046      0.000   -1.61e-13   -1.08e-13
C(date)[T.2022-07-17]  5.343e-14   1.34e-14      3.983      0.000    2.71e-14    7.97e-14
C(date)[T.2022-07-18]  4.073e-15   1.41e-14      0.288      0.773   -2.37e-14    3.18e-14
C(date)[T.2022-07-19] -1.332e-14   1.42e-14     -0.940      0.347   -4.11e-14    1.45e-14
C(date)[T.2022-07-20] -4.743e-14   1.52e-14     -3.122      0.002   -7.72e-14   -1.76e-14
C(date)[T.2022-07-21]  2.601e-14   8.36e-15      3.109      0.002    9.61e-15    4.24e-14
C(date)[T.2022-07-22] -5.528e-14   1.35e-14     -4.096      0.000   -8.17e-14   -2.88e-14
C(date)[T.2022-07-23] -7.599e-14   1.15e-14     -6.594      0.000   -9.86e-14   -5.34e-14
C(date)[T.2022-07-24] -2.463e-14   9.98e-15     -2.467      0.014   -4.42e-14   -5.06e-15
C(date)[T.2022-07-25]  9.883e-14   1.51e-14      6.542      0.000    6.92e-14    1.28e-13
C(date)[T.2022-07-26] -3.388e-14   1.22e-14     -2.770      0.006   -5.79e-14    -9.9e-15
C(date)[T.2022-07-27] -5.312e-14    1.1e-14     -4.808      0.000   -7.48e-14   -3.15e-14
C(date)[T.2022-07-28]   1.42e-14   7.14e-15      1.988      0.047    1.96e-16    2.82e-14
C(date)[T.2022-07-29]  9.055e-15   8.81e-15      1.028      0.304   -8.21e-15    2.63e-14
C(date)[T.2022-07-30]  2.268e-14   1.13e-14      2.000      0.046    4.45e-16    4.49e-14
C(date)[T.2022-07-31]  4.214e-14   1.05e-14      4.020      0.000    2.16e-14    6.27e-14
C(date)[T.2022-08-01]  1.173e-13   1.37e-14      8.579      0.000    9.05e-14    1.44e-13
C(date)[T.2022-08-02]  6.625e-15    1.4e-14      0.473      0.636   -2.08e-14    3.41e-14
C(date)[T.2022-08-03]  3.743e-14   8.69e-15      4.309      0.000    2.04e-14    5.45e-14
C(date)[T.2022-08-04] -1.608e-13   1.46e-14    -11.006      0.000   -1.89e-13   -1.32e-13
C(date)[T.2022-08-05]  1.002e-14   1.42e-14      0.707      0.480   -1.78e-14    3.78e-14
C(date)[T.2022-08-06] -8.661e-15   9.08e-15     -0.953      0.340   -2.65e-14    9.15e-15
C(date)[T.2022-08-07] -1.928e-14    1.1e-14     -1.758      0.079   -4.08e-14    2.21e-15
C(date)[T.2022-08-08]   2.76e-14   2.02e-14      1.368      0.171    -1.2e-14    6.71e-14
C(date)[T.2022-08-09] -5.131e-14   1.09e-14     -4.717      0.000   -7.26e-14      -3e-14
C(date)[T.2022-08-10]  2.658e-14   1.09e-14      2.428      0.015    5.12e-15     4.8e-14
C(date)[T.2022-08-11] -5.441e-14   9.63e-15     -5.649      0.000   -7.33e-14   -3.55e-14
C(date)[T.2022-08-12] -3.564e-14   7.11e-15     -5.013      0.000   -4.96e-14   -2.17e-14
C(date)[T.2022-08-13] -7.681e-14   1.38e-14     -5.585      0.000   -1.04e-13   -4.99e-14
C(date)[T.2022-08-14] -1.012e-14   1.07e-14     -0.948      0.343   -3.11e-14    1.08e-14
C(date)[T.2022-08-15] -1.441e-13   1.37e-14    -10.525      0.000   -1.71e-13   -1.17e-13
C(date)[T.2022-08-16]  4.123e-14   1.29e-14      3.201      0.001     1.6e-14    6.65e-14
C(date)[T.2022-08-17] -2.431e-13   2.23e-14    -10.900      0.000   -2.87e-13   -1.99e-13
C(date)[T.2022-08-18]  6.383e-14    1.2e-14      5.314      0.000    4.03e-14    8.74e-14

## interaction term => synnergetic effect

In [ ]:
reg_int = smf.ols("regular ~ distance * C(met) + C(date)", data = panel).fit()
print(reg_int.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                regular   R-squared:                       0.986
Model:                            OLS   Adj. R-squared:                  0.986
Method:                 Least Squares   F-statistic:                     1426.
Date:                Thu, 26 Mar 2026   Prob (F-statistic):               0.00
Time:                        04:03:51   Log-Likelihood:                 10739.
No. Observations:                6312   AIC:                        -2.087e+04
Df Residuals:                    6006   BIC:                        -1.880e+04
Df Model:                         305
Covariance Type:            nonrobust
==============================================================================================================================
                                                                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------------------
Intercept                                                      3.2697      0.015    224.616      0.000       3.241       3.298
C(met)[T.Crestview-Fort Walton Beach-Destin]                  -0.2514      0.008    -33.252      0.000      -0.266      -0.237
C(met)[T.Deltona-Daytona Beach-Ormond Beach]                  -0.0040      0.007     -0.535      0.593      -0.019       0.011
C(met)[T.Gainesville]                                          0.0548      0.007      7.360      0.000       0.040       0.069
C(met)[T.Homosassa Springs]                                    0.0205      0.007      2.772      0.006       0.006       0.035
C(met)[T.Jacksonville]                                        -0.0243      0.008     -3.223      0.001      -0.039      -0.010
C(met)[T.Lakeland-Winter Haven]                                0.0008      0.007      0.115      0.909      -0.014       0.015
C(met)[T.Miami-Fort Lauderdale-West Palm Beach]                0.0742      0.006     12.481      0.000       0.063       0.086
C(met)[T.Naples-Marco Island]                                  0.0747      0.007     10.268      0.000       0.060       0.089
C(met)[T.North Port-Bradenton-Sarasota]                        0.0002      0.007      0.023      0.982      -0.014       0.014
C(met)[T.Ocala]                                                0.0045      0.007      0.605      0.545      -0.010       0.019
C(met)[T.Orlando-Kissimmee-Sanford]                           -0.0208      0.007     -2.813      0.005      -0.035      -0.006
C(met)[T.Palm Bay-Melbourne-Titusville]                       -0.0335      0.007     -4.540      0.000      -0.048      -0.019
C(met)[T.Panama City-Panama City Beach]                       -0.2051      0.008    -27.255      0.000      -0.220      -0.190
C(met)[T.Pensacola-Ferry Pass-Brent]                          -0.2222      0.008    -29.335      0.000      -0.237      -0.207
C(met)[T.Port St. Lucie]                                       0.0247      0.007      3.369      0.001       0.010       0.039
C(met)[T.Punta Gorda]                                         -0.0316      0.007     -4.334      0.000      -0.046      -0.017
C(met)[T.Sebastian-Vero Beach-West Vero Corridor]             -0.0005      0.007     -0.066      0.947      -0.015       0.014
C(met)[T.Sebring]                                              0.0126      0.007      1.717      0.086      -0.002       0.027
C(met)[T.Tallahassee]                                         -0.0177      0.008     -2.352      0.019      -0.032      -0.003
C(met)[T.Tampa-St. Petersburg-Clearwater]                     -0.0006      0.007     -0.078      0.938      -0.015       0.014
C(met)[T.Wildwood-The Villages]                               -0.0259      0.007     -3.506      0.000      -0.040      -0.011
C(date)[T.2022-01-22]                                       6.538e-14   7.02e-15      9.312      0.000    5.16e-14    7.91e-14
C(date)[T.2022-01-23]                                       1.584e-15   4.76e-15      0.333      0.739   -7.74e-15    1.09e-14
C(date)[T.2022-01-24]                                       4.765e-14   5.68e-15      8.395      0.000    3.65e-14    5.88e-14
C(date)[T.2022-01-25]                                       7.842e-14   1.01e-14      7.740      0.000    5.86e-14    9.83e-14
C(date)[T.2022-01-26]                                       8.624e-14    3.2e-15     26.951      0.000       8e-14    9.25e-14
C(date)[T.2022-01-27]                                      -8.097e-14   2.65e-15    -30.549      0.000   -8.62e-14   -7.58e-14
C(date)[T.2022-01-28]                                      -3.406e-14   1.24e-15    -27.535      0.000   -3.65e-14   -3.16e-14
C(date)[T.2022-01-29]                                       -2.54e-14   7.08e-16    -35.862      0.000   -2.68e-14    -2.4e-14
C(date)[T.2022-01-30]                                       2.602e-14   9.37e-16     27.770      0.000    2.42e-14    2.79e-14
C(date)[T.2022-01-31]                                       2.599e-14   7.99e-16     32.543      0.000    2.44e-14    2.76e-14
C(date)[T.2022-02-01]                                      -2.946e-14   7.73e-16    -38.102      0.000    -3.1e-14   -2.79e-14
C(date)[T.2022-02-02]                                      -5.406e-16   6.62e-17     -8.166      0.000    -6.7e-16   -4.11e-16
C(date)[T.2022-02-03]                                      -7.627e-16   4.87e-17    -15.647      0.000   -8.58e-16   -6.67e-16
C(date)[T.2022-02-04]                                       3.114e-15   7.44e-17     41.861      0.000    2.97e-15    3.26e-15
C(date)[T.2022-02-05]                                      -9.354e-16   6.71e-17    -13.947      0.000   -1.07e-15   -8.04e-16
C(date)[T.2022-02-06]                                      -5.875e-15   7.33e-17    -80.179      0.000   -6.02e-15   -5.73e-15
C(date)[T.2022-02-07]                                      -3.069e-16    5.9e-17     -5.203      0.000   -4.22e-16   -1.91e-16
C(date)[T.2022-02-08]                                        2.57e-15   1.04e-16     24.702      0.000    2.37e-15    2.77e-15
C(date)[T.2022-02-09]                                       1.104e-15   7.43e-17     14.851      0.000    9.58e-16    1.25e-15
C(date)[T.2022-02-10]                                       -2.01e-15   6.14e-17    -32.741      0.000   -2.13e-15   -1.89e-15
C(date)[T.2022-02-11]                                      -1.058e-15   7.25e-17    -14.595      0.000    -1.2e-15   -9.16e-16
C(date)[T.2022-02-12]                                       -5.22e-16   4.76e-17    -10.968      0.000   -6.15e-16   -4.29e-16
C(date)[T.2022-02-13]                                      -1.824e-15   6.97e-17    -26.152      0.000   -1.96e-15   -1.69e-15
C(date)[T.2022-02-14]                                         3.2e-15   5.98e-17     53.497      0.000    3.08e-15    3.32e-15
C(date)[T.2022-02-15]                                      -1.767e-15   7.43e-17    -23.789      0.000   -1.91e-15   -1.62e-15
C(date)[T.2022-02-16]                                       -3.77e-16   5.41e-17     -6.974      0.000   -4.83e-16   -2.71e-16
C(date)[T.2022-02-17]                                      -1.458e-16   6.24e-17     -2.335      0.020   -2.68e-16   -2.34e-17
C(date)[T.2022-02-18]                                      -2.996e-15    5.1e-17    -58.697      0.000    -3.1e-15    -2.9e-15
C(date)[T.2022-02-19]                                       7.043e-17   8.57e-17      0.822      0.411   -9.75e-17    2.38e-16
C(date)[T.2022-02-20]                                      -1.315e-15   4.06e-17    -32.391      0.000   -1.39e-15   -1.24e-15
C(date)[T.2022-02-21]                                       2.791e-15   4.42e-17     63.118      0.000     2.7e-15    2.88e-15
C(date)[T.2022-02-22]                                       4.184e-16   6.18e-17      6.770      0.000    2.97e-16     5.4e-16
C(date)[T.2022-02-23]                                      -1.707e-15   9.18e-17    -18.596      0.000   -1.89e-15   -1.53e-15
C(date)[T.2022-02-24]                                       1.636e-15   7.76e-17     21.084      0.000    1.48e-15    1.79e-15
C(date)[T.2022-02-25]                                       1.504e-15   5.77e-17     26.055      0.000    1.39e-15    1.62e-15
C(date)[T.2022-02-26]                                       2.022e-15   4.82e-17     41.924      0.000    1.93e-15    2.12e-15
C(date)[T.2022-02-27]                                       3.068e-16   9.51e-17      3.227      0.001     1.2e-16    4.93e-16
C(date)[T.2022-02-28]                                      -4.441e-16   9.97e-17     -4.454      0.000    -6.4e-16   -2.49e-16
C(date)[T.2022-03-01]                                       3.885e-15   8.54e-17     45.485      0.000    3.72e-15    4.05e-15
C(date)[T.2022-03-02]                                      -2.018e-15   6.41e-17    -31.474      0.000   -2.14e-15   -1.89e-15
C(date)[T.2022-03-03]                                       2.569e-15   8.29e-17     31.003      0.000    2.41e-15    2.73e-15
C(date)[T.2022-03-04]                                        1.51e-15   7.37e-17     20.483      0.000    1.37e-15    1.65e-15
C(date)[T.2022-03-05]                                       6.067e-16   6.64e-17      9.133      0.000    4.76e-16    7.37e-16
C(date)[T.2022-03-06]                                       1.331e-17   6.32e-17      0.211      0.833   -1.11e-16    1.37e-16
C(date)[T.2022-03-07]                                        4.06e-16    7.7e-17      5.272      0.000    2.55e-16    5.57e-16
C(date)[T.2022-03-08]                                      -2.968e-15   4.93e-17    -60.238      0.000   -3.07e-15   -2.87e-15
C(date)[T.2022-03-09]                                       7.507e-16   4.46e-17     16.815      0.000    6.63e-16    8.38e-16
C(date)[T.2022-03-10]                                        9.77e-16   5.94e-17     16.435      0.000     8.6e-16    1.09e-15
C(date)[T.2022-03-11]                                      -1.414e-15    8.8e-17    -16.064      0.000   -1.59e-15   -1.24e-15
C(date)[T.2022-03-12]                                       2.701e-15   4.53e-17     59.641      0.000    2.61e-15    2.79e-15
C(date)[T.2022-03-13]                                       7.457e-16   4.98e-17     14.989      0.000    6.48e-16    8.43e-16
C(date)[T.2022-03-14]                                       1.879e-15    8.2e-17     22.904      0.000    1.72e-15    2.04e-15
C(date)[T.2022-03-15]                                      -2.254e-15   4.74e-17    -47.568      0.000   -2.35e-15   -2.16e-15
C(date)[T.2022-03-16]                                      -1.446e-15   6.69e-17    -21.608      0.000   -1.58e-15   -1.31e-15
C(date)[T.2022-03-17]                                      -3.131e-15   7.28e-17    -43.039      0.000   -3.27e-15   -2.99e-15
C(date)[T.2022-03-18]                                       2.861e-15   5.97e-17     47.960      0.000    2.74e-15    2.98e-15
C(date)[T.2022-03-19]                                       2.228e-15   6.87e-17     32.424      0.000    2.09e-15    2.36e-15
C(date)[T.2022-03-20]                                       1.861e-15   7.54e-17     24.681      0.000    1.71e-15    2.01e-15
C(date)[T.2022-03-21]                                       3.451e-16   6.94e-17      4.972      0.000    2.09e-16    4.81e-16
C(date)[T.2022-03-22]                                        1.33e-16   6.24e-17      2.133      0.033    1.07e-17    2.55e-16
C(date)[T.2022-03-23]                                       7.246e-16   7.52e-17      9.632      0.000    5.77e-16    8.72e-16
C(date)[T.2022-03-24]                                       5.757e-16   5.88e-17      9.796      0.000     4.6e-16    6.91e-16
C(date)[T.2022-03-25]                                       4.952e-17    3.6e-17      1.374      0.170   -2.11e-17     1.2e-16
C(date)[T.2022-03-26]                                      -4.644e-15   1.06e-16    -43.663      0.000   -4.85e-15   -4.44e-15
C(date)[T.2022-03-27]                                       2.152e-17   7.87e-17      0.274      0.784   -1.33e-16    1.76e-16
C(date)[T.2022-03-28]                                       1.745e-15   5.14e-17     33.969      0.000    1.64e-15    1.85e-15
C(date)[T.2022-03-29]                                       9.113e-16   7.86e-17     11.591      0.000    7.57e-16    1.07e-15
C(date)[T.2022-03-30]                                      -8.043e-16   1.05e-16     -7.689      0.000   -1.01e-15   -5.99e-16
C(date)[T.2022-03-31]                                      -5.378e-17   4.57e-17     -1.176      0.240   -1.43e-16    3.59e-17
C(date)[T.2022-04-01]                                       3.756e-15   1.02e-16     36.747      0.000    3.56e-15    3.96e-15
C(date)[T.2022-04-02]                                      -1.407e-15   9.74e-17    -14.443      0.000    -1.6e-15   -1.22e-15
C(date)[T.2022-04-03]                                      -8.631e-16   5.72e-17    -15.086      0.000   -9.75e-16   -7.51e-16
C(date)[T.2022-04-04]                                      -2.148e-15   6.24e-17    -34.406      0.000   -2.27e-15   -2.03e-15
C(date)[T.2022-04-05]                                      -3.411e-15   8.35e-17    -40.835      0.000   -3.58e-15   -3.25e-15
C(date)[T.2022-04-06]                                       1.063e-15   6.48e-17     16.397      0.000    9.36e-16    1.19e-15
C(date)[T.2022-04-07]                                      -3.777e-15   5.99e-17    -63.087      0.000   -3.89e-15   -3.66e-15
C(date)[T.2022-04-08]                                      -4.488e-16   8.75e-17     -5.128      0.000    -6.2e-16   -2.77e-16
C(date)[T.2022-04-09]                                       1.393e-15   5.54e-17     25.152      0.000    1.28e-15     1.5e-15
C(date)[T.2022-04-10]                                       5.007e-16   7.75e-17      6.465      0.000    3.49e-16    6.53e-16
C(date)[T.2022-04-11]                                      -1.431e-15   6.01e-17    -23.816      0.000   -1.55e-15   -1.31e-15
C(date)[T.2022-04-12]                                      -1.558e-15   7.22e-17    -21.587      0.000    -1.7e-15   -1.42e-15
C(date)[T.2022-04-13]                                      -4.868e-15   8.78e-17    -55.461      0.000   -5.04e-15    -4.7e-15
C(date)[T.2022-04-14]                                       -8.47e-16   6.05e-17    -14.000      0.000   -9.66e-16   -7.28e-16
C(date)[T.2022-04-15]                                       1.817e-15   7.01e-17     25.927      0.000    1.68e-15    1.95e-15
C(date)[T.2022-04-16]                                        5.96e-15   7.93e-17     75.154      0.000     5.8e-15    6.12e-15
C(date)[T.2022-04-17]                                        2.86e-15   5.69e-17     50.220      0.000    2.75e-15    2.97e-15
C(date)[T.2022-04-18]                                      -1.739e-15   4.51e-17    -38.572      0.000   -1.83e-15   -1.65e-15
C(date)[T.2022-04-19]                                       1.458e-15   5.67e-17     25.732      0.000    1.35e-15    1.57e-15
C(date)[T.2022-04-20]                                      -1.403e-15   7.85e-17    -17.874      0.000   -1.56e-15   -1.25e-15
C(date)[T.2022-04-21]                                       2.656e-15   5.99e-17     44.347      0.000    2.54e-15    2.77e-15
C(date)[T.2022-04-22]                                      -1.006e-15   7.16e-17    -14.056      0.000   -1.15e-15   -8.66e-16
C(date)[T.2022-04-23]                                       9.033e-16   4.99e-17     18.093      0.000    8.05e-16       1e-15
C(date)[T.2022-04-24]                                       2.188e-15   6.63e-17     33.017      0.000    2.06e-15    2.32e-15
C(date)[T.2022-04-25]                                      -1.526e-15   7.26e-17    -21.023      0.000   -1.67e-15   -1.38e-15
C(date)[T.2022-04-26]                                      -3.836e-15   6.32e-17    -60.695      0.000   -3.96e-15   -3.71e-15
C(date)[T.2022-04-27]                                       3.358e-15   7.71e-17     43.542      0.000    3.21e-15    3.51e-15
C(date)[T.2022-04-28]                                      -1.517e-15    6.8e-17    -22.316      0.000   -1.65e-15   -1.38e-15
C(date)[T.2022-04-29]                                      -7.765e-16   5.66e-17    -13.720      0.000   -8.87e-16   -6.66e-16
C(date)[T.2022-04-30]                                      -6.573e-16   6.04e-17    -10.887      0.000   -7.76e-16   -5.39e-16
C(date)[T.2022-05-01]                                       4.246e-15   8.59e-17     49.408      0.000    4.08e-15    4.41e-15
C(date)[T.2022-05-02]                                      -2.819e-15   9.07e-17    -31.075      0.000      -3e-15   -2.64e-15
C(date)[T.2022-05-03]                                      -2.704e-15   9.17e-17    -29.478      0.000   -2.88e-15   -2.52e-15
C(date)[T.2022-05-04]                                      -2.519e-15   5.82e-17    -43.303      0.000   -2.63e-15   -2.41e-15
C(date)[T.2022-05-05]                                       2.959e-15   6.33e-17     46.744      0.000    2.84e-15    3.08e-15
C(date)[T.2022-05-06]                                       3.764e-16   7.29e-17      5.162      0.000    2.33e-16    5.19e-16
C(date)[T.2022-05-07]                                      -5.475e-15    8.4e-17    -65.204      0.000   -5.64e-15   -5.31e-15
C(date)[T.2022-05-08]                                      -7.098e-16   7.28e-17     -9.746      0.000   -8.53e-16   -5.67e-16
C(date)[T.2022-05-09]                                      -3.625e-16    6.5e-17     -5.577      0.000    -4.9e-16   -2.35e-16
C(date)[T.2022-05-10]                                       3.119e-15   1.04e-16     30.128      0.000    2.92e-15    3.32e-15
C(date)[T.2022-05-11]                                        2.48e-15   7.71e-17     32.176      0.000    2.33e-15    2.63e-15
C(date)[T.2022-05-12]                                       3.913e-15    8.2e-17     47.695      0.000    3.75e-15    4.07e-15
C(date)[T.2022-05-13]                                       3.883e-15   8.67e-17     44.774      0.000    3.71e-15    4.05e-15
C(date)[T.2022-05-14]                                       7.005e-16   4.09e-17     17.144      0.000     6.2e-16    7.81e-16
C(date)[T.2022-05-15]                                       3.163e-15   8.88e-17     35.606      0.000    2.99e-15    3.34e-15
C(date)[T.2022-05-16]                                       4.375e-15   1.16e-16     37.654      0.000    4.15e-15     4.6e-15
C(date)[T.2022-05-17]                                       1.289e-15   4.97e-17     25.918      0.000    1.19e-15    1.39e-15
C(date)[T.2022-05-18]                                       3.594e-15   8.52e-17     42.188      0.000    3.43e-15    3.76e-15
C(date)[T.2022-05-19]                                        7.24e-16   5.32e-17     13.618      0.000     6.2e-16    8.28e-16
C(date)[T.2022-05-20]                                       5.361e-16   5.24e-17     10.229      0.000    4.33e-16    6.39e-16
C(date)[T.2022-05-21]                                      -4.233e-15   7.88e-17    -53.732      0.000   -4.39e-15   -4.08e-15
C(date)[T.2022-05-22]                                       2.349e-15   7.36e-17     31.914      0.000     2.2e-15    2.49e-15
C(date)[T.2022-05-23]                                       -1.78e-15   6.99e-17    -25.448      0.000   -1.92e-15   -1.64e-15
C(date)[T.2022-05-24]                                       1.307e-15    5.5e-17     23.756      0.000     1.2e-15    1.41e-15
C(date)[T.2022-05-25]                                       -1.91e-15   8.16e-17    -23.399      0.000   -2.07e-15   -1.75e-15
C(date)[T.2022-05-26]                                      -1.422e-15   8.34e-17    -17.047      0.000   -1.59e-15   -1.26e-15
C(date)[T.2022-05-27]                                       1.853e-15      6e-17     30.870      0.000    1.74e-15    1.97e-15