In [10]:
from src.scraping import run_scrape
import pandas as pd

## Notebook scraped file

### Running function from src

In [ ]:
df = run_scrape(max_days=5, sleep_s = 0.3)

CDX: listing captures for https://gasprices.aaa.com/?state=FL from 2022 to 2025 ...
Found 682 captures -> 5 daily captures.
Resuming: 50 dates already in aaa_fl_metros_wayback_2022_2025.csv will be skipped.

Empty DataFrame
Columns: []
Index: []

### EDA on the CSV produced

In [11]:
gas = pd.read_csv("aaa_fl_metros_wayback_2022_2025.csv")
gas.head()

,date,wayback_timestamp,metro,label,regular,mid,premium,diesel
0,2022-01-28,20220128192222,Bradenton-Sarasota-Venice,Current Avg.,3.351,3.731,4.006,3.716
1,2022-01-28,20220128192222,Bradenton-Sarasota-Venice,Yesterday Avg.,3.348,3.709,4.003,3.711
2,2022-01-28,20220128192222,Bradenton-Sarasota-Venice,Week Ago Avg.,3.236,3.625,3.915,3.563
3,2022-01-28,20220128192222,Bradenton-Sarasota-Venice,Month Ago Avg.,3.213,3.602,3.899,3.478
4,2022-01-28,20220128192222,Bradenton-Sarasota-Venice,Year Ago Avg.,2.366,2.726,3.014,2.617

In [15]:
print(len(gas))
gas['regular'].mean()

21600

np.float64(3.386628287037037)